#!/usr/bin/env python3
"""
Generic Test Data Generator for File Organizer
==============================================

Generates realistic test documents with generic filenames like a ScanSnap S1300
would produce. This forces the local LLM to analyze content to determine:
1. Document type (bank statement, medical bill, etc.)
2. Date for organization
3. Vendor/institution name
4. Appropriate folder assignment

Filenames follow ScanSnap format: Scan_YYYYMMDD_XXXX.txt
"""

import os
import random
import shutil
from datetime import datetime, timedelta
from pathlib import Path
from typing import List

# Fake data generators
FIRST_NAMES = ["James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", 
               "William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica"]
LAST_NAMES = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
              "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson"]
STREET_NAMES = ["Main", "Oak", "Pine", "Cedar", "Maple", "Elm", "Washington", "Lake", "Hill"]
CITIES = ["Phoenix", "Scottsdale", "Tempe", "Mesa", "Glendale", "Chandler", "Gilbert"]
STATES = ["AZ", "CA", "TX", "FL", "CO", "NV", "UT", "NM"]
COMPANIES = ["TechCorp Solutions", "Desert Dynamics", "Summit Innovations", "Canyon Creek LLC"]

NOT_REAL_HEADER = """
╔══════════════════════════════════════════════════════════════════════════════╗
║  ⚠️  THIS IS A TEST DOCUMENT - NOT REAL - FOR TESTING PURPOSES ONLY ⚠️        ║
║  Generated by File Organizer Test Suite - DO NOT USE FOR ANY OFFICIAL PURPOSE ║
╚══════════════════════════════════════════════════════════════════════════════╝

"""

NOT_REAL_FOOTER = """

═══════════════════════════════════════════════════════════════════════════════
⚠️  FICTITIOUS DOCUMENT - GENERATED FOR SOFTWARE TESTING - NOT REAL ⚠️
Document ID: TEST-{doc_id} | Generated: {timestamp} | Hash: {hash_val}
This document contains no real personal information or financial data.
═══════════════════════════════════════════════════════════════════════════════
"""

def fake_name():
    return f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}"

def fake_street():
    return f"{random.randint(100, 9999)} {random.choice(STREET_NAMES)} {random.choice(['St', 'Ave', 'Blvd'])}"

def fake_address():
    return f"{fake_street()}, {random.choice(CITIES)}, {random.choice(STATES)} {random.randint(10000, 99999)}"

def fake_company():
    return random.choice(COMPANIES)

def fake_ssn():
    return f"XXX-XX-{random.randint(1000, 9999)}"

def fake_phone():
    return f"({random.randint(200, 999)}) {random.randint(100, 999)}-{random.randint(1000, 9999)}"


class DocumentGenerator:
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.doc_counter = 0
        
    def generate_doc_id(self) -> str:
        self.doc_counter += 1
        return f"DOC{self.doc_counter:04d}"
    
    def add_not_real_markers(self, content: str, doc_id: str) -> str:
        timestamp = datetime.now().isoformat()
        hash_val = hex(hash(doc_id + timestamp) & 0xFFFFFF)[2:].upper().zfill(6)
        footer = NOT_REAL_FOOTER.format(doc_id=doc_id, timestamp=timestamp, hash_val=hash_val)
        return NOT_REAL_HEADER + content + footer
    
    def save(self, filename: str, content: str, doc_id: str) -> Path:
        full_content = self.add_not_real_markers(content, doc_id)
        filepath = self.output_dir / filename
        filepath.write_text(full_content)
        return filepath


class BankStatementGenerator(DocumentGenerator):
    BANKS = [
        ("Chase Bank", "JPMorgan Chase Bank, N.A.", "P.O. Box 659754, San Antonio, TX 78265-9754"),
        ("Wells Fargo", "Wells Fargo Bank, N.A.", "P.O. Box 6995, Portland, OR 97228-6995"),
        ("Bank of America", "Bank of America, N.A.", "P.O. Box 15019, Wilmington, DE 19886-5019"),
        ("Citibank", "Citibank, N.A.", "P.O. Box 769007, San Antonio, TX 78245-9007"),
    ]
    
    def generate(self, count: int = 1) -> List[Path]:
        files = []
        for _ in range(count):
            bank_name, bank_legal, bank_address = random.choice(self.BANKS)
            doc_id = self.generate_doc_id()
            stmt_date = datetime.now() - timedelta(days=random.randint(1, 730))
            account_num = f"****{random.randint(1000, 9999)}"
            
            content = f"""
{'='*80}
                           {bank_name.upper()}
                         Monthly Account Statement
{'='*80}

{bank_legal}
{bank_address}

Statement Period: {stmt_date.strftime('%B %d, %Y')} - {(stmt_date + timedelta(days=30)).strftime('%B %d, %Y')}
Statement Date: {(stmt_date + timedelta(days=30)).strftime('%B %d, %Y')}

PRIMARY ACCOUNT HOLDER
{fake_name()}
{fake_street()}
{fake_address().split(', ')[1]}

Account Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Account Number:          {account_num}
Account Type:            {'Checking' if random.random() > 0.5 else 'Savings'}
Beginning Balance:       ${random.uniform(1000, 15000):,.2f}
Deposits/Credits:        ${random.uniform(500, 8000):,.2f}
Withdrawals/Debits:      ${random.uniform(400, 7500):,.2f}
Ending Balance:          ${random.uniform(1000, 15000):,.2f}

Transaction History
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Date          Description                                    Amount    Balance
------------------------------------------------------------------------------
"""
            balance = random.uniform(1000, 15000)
            current_date = stmt_date
            for i in range(random.randint(15, 30)):
                current_date += timedelta(days=random.randint(0, 2))
                if current_date > stmt_date + timedelta(days=30):
                    break
                transaction_types = [
                    ("POS Purchase - Grocery Store", -random.uniform(20, 200)),
                    ("Direct Deposit - Employer", random.uniform(1000, 5000)),
                    ("ATM Withdrawal", -random.uniform(20, 500)),
                    ("Online Payment - Utility", -random.uniform(50, 300)),
                    ("Monthly Service Fee", -random.uniform(5, 25)),
                ]
                desc, amount = random.choice(transaction_types)
                balance += amount
                content += f"{current_date.strftime('%m/%d/%Y')}  {desc:<45} ${amount:>8,.2f}  ${balance:>10,.2f}\n"
            
            content += f"""
------------------------------------------------------------------------------
Ending Balance:                                              ${balance:>10,.2f}

Important Information
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Questions about your statement? Call 1-800-{random.randint(100, 999)}-{random.randint(1000, 9999)}
Available 24 hours a day, 7 days a week.
"""
            # Generic filename - LLM must figure out it's a bank statement
            filename = f"Scan_{stmt_date.strftime('%Y%m%d')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append((filepath, bank_name, stmt_date, "Bank Statement"))
        return files


class MedicalBillGenerator(DocumentGenerator):
    PROVIDERS = [
        ("Sunrise Medical Center", "1234 Healthcare Blvd", "Medical City, ST 12345"),
        ("Metro General Hospital", "5678 Wellness Way", "Healthville, ST 67890"),
        ("Valley Regional Medical", "9012 Cure Street", "Medtown, ST 11111"),
    ]
    
    PROCEDURES = [
        ("Office Visit - Established Patient", 150, 45),
        ("Annual Physical Examination", 250, 75),
        ("Blood Test - Comprehensive Metabolic Panel", 180, 35),
        ("Chest X-Ray", 320, 80),
        ("MRI - Lumbar Spine", 2200, 550),
        ("CT Scan - Head", 1800, 450),
        ("Emergency Room Visit", 2800, 700),
    ]
    
    def generate(self, count: int = 1) -> List[Path]:
        files = []
        for _ in range(count):
            provider, address, location = random.choice(self.PROVIDERS)
            doc_id = self.generate_doc_id()
            bill_date = datetime.now() - timedelta(days=random.randint(1, 180))
            patient_name = fake_name()
            
            content = f"""
{'='*80}
                        {provider.upper()}
                           STATEMENT OF SERVICES
{'='*80}

{provider}
{address}
{location}
Phone: {fake_phone()}
Fax: {fake_phone()}

STATEMENT DATE: {bill_date.strftime('%B %d, %Y')}
STATEMENT NUMBER: MED-{random.randint(100000, 999999)}
PATIENT ACCOUNT: {random.randint(10000000, 99999999)}

PATIENT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Patient Name:     {patient_name}
Date of Birth:    {random.randint(1,12)}/{random.randint(1,28)}/{random.randint(1950,2000)}
Address:          {fake_street()}
                  {fake_address().split(', ')[1]}
Insurance:        {random.choice(['Blue Cross Blue Shield', 'Aetna', 'UnitedHealthcare', 'Self Pay'])}

SERVICE DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Date of Service:  {(bill_date - timedelta(days=random.randint(7, 30))).strftime('%m/%d/%Y')}
Provider:         Dr. {random.choice(LAST_NAMES)}, {random.choice(['MD', 'DO', 'NP', 'PA'])}

PROCEDURES AND CHARGES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Code    Description                                    Charge      Insurance    You Owe
────────────────────────────────────────────────────────────────────────────────────────
"""
            total_charge = 0
            total_insurance = 0
            total_patient = 0
            
            for i in range(random.randint(1, 5)):
                proc_name, charge, patient_owes = random.choice(self.PROCEDURES)
                insurance_pays = charge - patient_owes
                code = f"{random.randint(10000, 99999)}"
                content += f"{code}  {proc_name:<45} ${charge:>8,.2f}   ${insurance_pays:>8,.2f}   ${patient_owes:>7,.2f}\n"
                total_charge += charge
                total_insurance += insurance_pays
                total_patient += patient_owes
            
            content += f"""
────────────────────────────────────────────────────────────────────────────────────────
TOTALS:                                              ${total_charge:>8,.2f}   ${total_insurance:>8,.2f}   ${total_patient:>7,.2f}

PAYMENT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Charges:                                      ${total_charge:>10,.2f}
Insurance Payments/Adjustments:                     -${total_insurance:>10,.2f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AMOUNT DUE:                                         ${total_patient:>10,.2f}

PAYMENT DUE BY: {(bill_date + timedelta(days=30)).strftime('%B %d, %Y')}

PAYMENT OPTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Online: www.{provider.lower().replace(' ', '')}.com/pay
• Phone: {fake_phone()}
• Mail: {provider}, Billing Department, {address}, {location}

If you have questions about this statement, please contact our billing department
at {fake_phone()}, Monday-Friday, 8am-5pm.
"""
            # Generic filename - LLM must figure out it's a medical bill
            filename = f"Scan_{bill_date.strftime('%Y%m%d')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append((filepath, provider, bill_date, "Medical Bill"))
        return files


class UtilityBillGenerator(DocumentGenerator):
    UTILITIES = [
        ("Arizona Public Service", "Electric", "Phoenix, AZ 85001"),
        ("Salt River Project", "Electric", "Tempe, AZ 85284"),
        ("Southwest Gas", "Gas", "Phoenix, AZ 85072"),
        ("City of Phoenix Water", "Water", "Phoenix, AZ 85003"),
        ("Cox Communications", "Internet/Cable", "Phoenix, AZ 85034"),
    ]
    
    def generate(self, count: int = 1) -> List[Path]:
        files = []
        for _ in range(count):
            utility, service_type, location = random.choice(self.UTILITIES)
            doc_id = self.generate_doc_id()
            bill_date = datetime.now() - timedelta(days=random.randint(1, 90))
            
            content = f"""
{'='*80}
                          {utility.upper()}
                        {service_type.upper()} SERVICE BILL
{'='*80}

{utility}
Billing Department
{location}
Customer Service: 1-800-{random.randint(100, 999)}-{random.randint(1000, 9999)}

BILLING INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Account Number:   {random.randint(100000000, 999999999)}
Bill Date:        {bill_date.strftime('%B %d, %Y')}
Service Period:   {(bill_date - timedelta(days=30)).strftime('%m/%d/%Y')} - {bill_date.strftime('%m/%d/%Y')}
Due Date:         {(bill_date + timedelta(days=15)).strftime('%B %d, %Y')}

SERVICE ADDRESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{fake_address()}

ACCOUNT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Previous Balance:                                   ${random.uniform(80, 300):>10,.2f}
Payments Received:                                  -${random.uniform(80, 300):>10,.2f}
Current Charges:                                    ${random.uniform(50, 400):>10,.2f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Amount Due:                                   ${random.uniform(50, 400):>10,.2f}

USAGE DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Meter Number:     {random.randint(10000000, 99999999)}
Previous Reading: {random.randint(10000, 99999)}
Current Reading:  {random.randint(10000, 99999)}

CHARGE DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{service_type} Service Charge:                      ${random.uniform(10, 20):>10,.2f}
Energy/Delivery Charges:                            ${random.uniform(30, 200):>10,.2f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Current Charges:                              ${random.uniform(50, 400):>10,.2f}

PAYMENT OPTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• Online: Pay at www.{utility.lower().replace(' ', '').replace('(', '').replace(')', '')}.com
• AutoPay: Enroll for automatic monthly payments
• Phone: 1-800-{random.randint(100, 999)}-{random.randint(1000, 9999)}

LATE PAYMENT WARNING
If payment is not received by {(bill_date + timedelta(days=15)).strftime('%B %d, %Y')},
a late fee of ${random.uniform(5, 25):.2f} may be applied.

This utility bill is generated for testing purposes only.
"""
            # Generic filename - LLM must figure out it's a utility bill
            filename = f"Scan_{bill_date.strftime('%Y%m%d')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append((filepath, utility, bill_date, "Utility Bill"))
        return files


class TaxDocumentGenerator(DocumentGenerator):
    def generate_w2(self, count: int = 1) -> List[Path]:
        files = []
        tax_year = datetime.now().year - 1
        
        for _ in range(count):
            doc_id = self.generate_doc_id()
            employer = fake_company()
            employee = fake_name()
            wages = random.uniform(35000, 150000)
            
            content = f"""
{'='*80}
                    W-2 WAGE AND TAX STATEMENT {tax_year}
{'='*80}

                           ▓▓▓▓  ⚠️  DUMMY TAX DOCUMENT - NOT REAL  ⚠️  ▓▓▓▓

Employer: {employer}
Employee: {employee}
SSN: {fake_ssn()}

WAGE AND TAX INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Box 1 - Wages, tips, other compensation:              ${wages:>12,.2f}
Box 2 - Federal income tax withheld:                  ${wages * 0.12:>12,.2f}
Box 3 - Social Security wages:                        ${min(wages, 168600):>12,.2f}
Box 4 - Social Security tax withheld:                 ${min(wages, 168600) * 0.062:>12,.2f}
Box 5 - Medicare wages and tips:                      ${wages:>12,.2f}
Box 6 - Medicare tax withheld:                        ${wages * 0.0145:>12,.2f}

This is a test document. Do not use for actual tax filing.
"""
            # Generic filename - LLM must figure out it's a tax document
            filename = f"Scan_{datetime.now().strftime('%Y%m%d')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append((filepath, employer, datetime.now(), "Tax Document (W-2)"))
        return files


class CreditCardStatementGenerator(DocumentGenerator):
    ISSUERS = [
        ("Chase Freedom", "Chase Bank USA, N.A."),
        ("Citi Double Cash", "Citibank, N.A."),
        ("Amex Blue Cash", "American Express"),
        ("Discover It", "Discover Bank"),
    ]
    
    def generate(self, count: int = 1) -> List[Path]:
        files = []
        for _ in range(count):
            card_name, issuer = random.choice(self.ISSUERS)
            doc_id = self.generate_doc_id()
            stmt_date = datetime.now() - timedelta(days=random.randint(1, 730))
            
            content = f"""
{'='*80}
                         {card_name.upper()}
                        CREDIT CARD STATEMENT
{'='*80}

{issuer}
Customer Service: 1-800-{random.randint(100, 999)}-{random.randint(1000, 9999)}

STATEMENT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Statement Date:   {stmt_date.strftime('%B %d, %Y')}
Card Number:      ****-****-****-{random.randint(1000, 9999)}
Cardholder:       {fake_name()}

Account Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Previous Balance:                                   ${random.uniform(500, 3000):>10,.2f}
Payments/Credits:                                   -${random.uniform(400, 3000):>10,.2f}
Purchases/Charges:                                  ${random.uniform(200, 2500):>10,.2f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NEW BALANCE:                                        ${random.uniform(100, 4000):>10,.2f}

Minimum Payment Due:                                ${random.uniform(25, 150):>10,.2f}
Payment Due Date:                                   {(stmt_date + timedelta(days=25)).strftime('%B %d, %Y')}

This credit card statement is generated for testing purposes only.
"""
            # Generic filename - LLM must figure out it's a credit card statement
            filename = f"Scan_{stmt_date.strftime('%Y%m%d')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append((filepath, card_name, stmt_date, "Credit Card Statement"))
        return files


def generate_scansnap_test_data(output_dir: Path, count_per_type: int = 3):
    """
    Generate test data with generic ScanSnap-style filenames.
    
    Returns manifest of what was generated so you can verify the LLM
    correctly identified each document.
    """
    manifest = []
    
    print(f"Generating test data in: {output_dir.absolute()}")
    print(f"Files per type: {count_per_type}")
    print()
    
    # Clear existing files
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print("Generating bank statements...")
    bank_gen = BankStatementGenerator(output_dir)
    bank_files = bank_gen.generate(count_per_type)
    manifest.extend(bank_files)
    
    print("Generating medical bills...")
    medical_gen = MedicalBillGenerator(output_dir)
    medical_files = medical_gen.generate(count_per_type)
    manifest.extend(medical_files)
    
    print("Generating utility bills...")
    utility_gen = UtilityBillGenerator(output_dir)
    utility_files = utility_gen.generate(count_per_type)
    manifest.extend(utility_files)
    
    print("Generating tax documents...")
    tax_gen = TaxDocumentGenerator(output_dir)
    tax_files = tax_gen.generate_w2(count_per_type)
    manifest.extend(tax_files)
    
    print("Generating credit card statements...")
    cc_gen = CreditCardStatementGenerator(output_dir)
    cc_files = cc_gen.generate(count_per_type)
    manifest.extend(cc_files)
    
    # Write manifest
    manifest_path = output_dir / "MANIFEST.txt"
    with open(manifest_path, 'w') as f:
        f.write("TEST DATA MANIFEST\n")
        f.write("="*80 + "\n")
        f.write("This file contains the ground truth for all generated test documents.\n")
        f.write("The LLM should be able to determine the correct type from content alone.\n\n")
        
        for filepath, source, date, doc_type in manifest:
            f.write(f"\nFile: {filepath.name}\n")
            f.write(f"  Expected Type: {doc_type}\n")
            f.write(f"  Source: {source}\n")
            f.write(f"  Date: {date.strftime('%Y-%m-%d')}\n")
    
    print()
    print("="*60)
    print("TEST DATA GENERATION COMPLETE")
    print("="*60)
    print(f"\nTotal files generated: {len(manifest)}")
    print(f"All files have generic names: Scan_YYYYMMDD_XXXX.txt")
    print(f"Manifest saved to: {manifest_path}")
    print("\n⚠️  IMPORTANT: All files are marked as NOT REAL / TEST DATA")
    print("\nThe LLM must analyze content to:")
    print("  1. Identify document type (bank, medical, utility, tax, credit)")
    print("  2. Extract date for organization")
    print("  3. Identify vendor/institution name")
    print("  4. Suggest appropriate folder structure")
    
    return manifest


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate test data with generic ScanSnap filenames")
    parser.add_argument('--output', '-o', type=Path, default=Path(__file__).parent / "scansnap_test_data",
                        help='Output directory (default: ./scansnap_test_data)')
    parser.add_argument('--count', '-c', type=int, default=3,
                        help='Files per document type (default: 3)')
    
    args = parser.parse_args()
    generate_scansnap_test_data(args.output, args.count)
