"""
Test Data Generator for File Organizer
======================================

Generates realistic-looking dummy documents that simulate ScanSnap S1300 scanner output.
All documents are clearly marked as NOT REAL for testing purposes only.
"""

import os
import random
import argparse
from datetime import datetime, timedelta
from pathlib import Path
from typing import List


# Document templates with clearly marked fake indicators
NOT_REAL_HEADER = """
╔══════════════════════════════════════════════════════════════════════════════╗
║  ⚠️  THIS IS A TEST DOCUMENT - NOT REAL - FOR TESTING PURPOSES ONLY ⚠️        ║
║  Generated by File Organizer Test Suite - DO NOT USE FOR ANY OFFICIAL PURPOSE ║
╚══════════════════════════════════════════════════════════════════════════════╝

"""

NOT_REAL_FOOTER = """

═══════════════════════════════════════════════════════════════════════════════
⚠️  FICTITIOUS DOCUMENT - GENERATED FOR SOFTWARE TESTING - NOT REAL ⚠️
Document ID: TEST-{doc_id} | Generated: {timestamp} | Hash: {hash_val}
This document contains no real personal information or financial data.
═══════════════════════════════════════════════════════════════════════════════
"""

# Fake data generators (no external dependencies)
FIRST_NAMES = ["James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", 
               "William", "Elizabeth", "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica"]

LAST_NAMES = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
              "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson"]

STREET_NAMES = ["Main", "Oak", "Pine", "Cedar", "Maple", "Elm", "Washington", "Lake", "Hill"]
CITIES = ["Phoenix", "Scottsdale", "Tempe", "Mesa", "Glendale", "Chandler", "Gilbert"]
STATES = ["AZ", "CA", "TX", "FL", "CO", "NV", "UT", "NM"]
COMPANIES = ["TechCorp Solutions", "Desert Dynamics", "Summit Innovations", "Canyon Creek LLC"]


def fake_name():
    return f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}"


def fake_street():
    return f"{random.randint(100, 9999)} {random.choice(STREET_NAMES)} {random.choice(['St', 'Ave', 'Blvd'])}"


def fake_address():
    return f"{fake_street()}, {random.choice(CITIES)}, {random.choice(STATES)} {random.randint(10000, 99999)}"


def fake_company():
    return random.choice(COMPANIES)


def fake_ssn():
    return f"{random.randint(100, 999)}-{random.randint(10, 99)}-{random.randint(1000, 9999)}"


def fake_phone():
    return f"({random.randint(200, 999)}) {random.randint(100, 999)}-{random.randint(1000, 9999)}"


class DocumentGenerator:
    """Base class for generating test documents."""
    
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.doc_counter = 0
        
    def generate_doc_id(self) -> str:
        """Generate a unique document ID."""
        self.doc_counter += 1
        return f"{self.__class__.__name__.upper()[:4]}-{datetime.now().strftime('%Y%m%d')}-{self.doc_counter:04d}"
    
    def add_not_real_markers(self, content: str, doc_id: str) -> str:
        """Add NOT REAL markers to document content."""
        timestamp = datetime.now().isoformat()
        hash_val = hex(hash(doc_id + timestamp) & 0xFFFFFF)[2:].upper().zfill(6)
        footer = NOT_REAL_FOOTER.format(doc_id=doc_id, timestamp=timestamp, hash_val=hash_val)
        return NOT_REAL_HEADER + content + footer
    
    def save(self, filename: str, content: str, doc_id: str) -> Path:
        """Save document with NOT REAL markers."""
        full_content = self.add_not_real_markers(content, doc_id)
        filepath = self.output_dir / filename
        filepath.write_text(full_content)
        return filepath


class BankStatementGenerator(DocumentGenerator):
    """Generate dummy bank statements."""
    
    BANKS = [
        ("Chase Bank", "JPMorgan Chase Bank, N.A.", "P.O. Box 659754, San Antonio, TX 78265-9754"),
        ("Wells Fargo", "Wells Fargo Bank, N.A.", "P.O. Box 6995, Portland, OR 97228-6995"),
        ("Bank of America", "Bank of America, N.A.", "P.O. Box 15019, Wilmington, DE 19886-5019"),
        ("Citibank", "Citibank, N.A.", "P.O. Box 769007, San Antonio, TX 78245-9007"),
    ]
    
    def generate(self, count: int = 1) -> List[Path]:
        files = []
        for _ in range(count):
            bank_name, bank_legal, bank_address = random.choice(self.BANKS)
            doc_id = self.generate_doc_id()
            stmt_date = datetime.now() - timedelta(days=random.randint(1, 730))
            account_num = f"****{random.randint(1000, 9999)}"
            
            content = f"""
{'='*80}
                           {bank_name.upper()}
                         Monthly Account Statement
{'='*80}

{bank_legal}
{bank_address}

Statement Period: {stmt_date.strftime('%B %d, %Y')} - {(stmt_date + timedelta(days=30)).strftime('%B %d, %Y')}
Statement Date: {(stmt_date + timedelta(days=30)).strftime('%B %d, %Y')}

PRIMARY ACCOUNT HOLDER
{fake_name()}
{fake_street()}
{fake_address().split(', ')[1]}

Account Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Account Number:          {account_num}
Account Type:            {'Checking' if random.random() > 0.5 else 'Savings'}
Beginning Balance:       ${random.uniform(1000, 15000):,.2f}
Deposits/Credits:        ${random.uniform(500, 8000):,.2f}
Withdrawals/Debits:      ${random.uniform(400, 7500):,.2f}
Ending Balance:          ${random.uniform(1000, 15000):,.2f}

Transaction History
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Date          Description                                    Amount    Balance
------------------------------------------------------------------------------
"""
            balance = random.uniform(1000, 15000)
            current_date = stmt_date
            for i in range(random.randint(15, 30)):
                current_date += timedelta(days=random.randint(0, 2))
                if current_date > stmt_date + timedelta(days=30):
                    break
                transaction_types = [
                    ("POS Purchase - Grocery Store", -random.uniform(20, 200)),
                    ("Direct Deposit - Employer", random.uniform(1000, 5000)),
                    ("ATM Withdrawal", -random.uniform(20, 500)),
                    ("Online Payment - Utility", -random.uniform(50, 300)),
                    ("Monthly Service Fee", -random.uniform(5, 25)),
                ]
                desc, amount = random.choice(transaction_types)
                balance += amount
                content += f"{current_date.strftime('%m/%d/%Y')}  {desc:<45} ${amount:>8,.2f}  ${balance:>10,.2f}\n"
            
            content += f"""
------------------------------------------------------------------------------
Ending Balance:                                              ${balance:>10,.2f}

Important Information
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Questions about your statement? Call 1-800-{random.randint(100, 999)}-{random.randint(1000, 9999)}
Available 24 hours a day, 7 days a week.
"""
            
            filename = f"bank_statement_{bank_name.replace(' ', '_').lower()}_{stmt_date.strftime('%Y_%m')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append(filepath)
        return files


class MedicalBillGenerator(DocumentGenerator):
    """Generate dummy medical bills."""
    
    PROVIDERS = [
        ("Sunrise Medical Center", "1234 Healthcare Blvd", "Medical City, ST 12345"),
        ("Metro General Hospital", "5678 Wellness Way", "Healthville, ST 67890"),
        ("Valley Regional Medical", "9012 Cure Street", "Medtown, ST 11111"),
    ]
    
    PROCEDURES = [
        ("Office Visit - Established Patient", 150, 45),
        ("Annual Physical Examination", 250, 75),
        ("Blood Test - Comprehensive Metabolic Panel", 180, 35),
        ("Chest X-Ray", 320, 80),
        ("MRI - Lumbar Spine", 2200, 550),
        ("CT Scan - Head", 1800, 450),
        ("Emergency Room Visit", 2800, 700),
    ]
    
    def generate(self, count: int = 1) -> List[Path]:
        files = []
        for _ in range(count):
            provider, address, location = random.choice(self.PROVIDERS)
            doc_id = self.generate_doc_id()
            bill_date = datetime.now() - timedelta(days=random.randint(1, 180))
            patient_name = fake_name()
            
            content = f"""
{'='*80}
                        {provider.upper()}
                           STATEMENT OF SERVICES
{'='*80}

{provider}
{address}
{location}
Phone: {fake_phone()}
Fax: {fake_phone()}

STATEMENT DATE: {bill_date.strftime('%B %d, %Y')}
STATEMENT NUMBER: MED-{random.randint(100000, 999999)}
PATIENT ACCOUNT: {random.randint(10000000, 99999999)}

PATIENT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Patient Name:     {patient_name}
Date of Birth:    {random.randint(1,12)}/{random.randint(1,28)}/{random.randint(1950,2000)}
Address:          {fake_street()}
                  {fake_address().split(', ')[1]}
Insurance:        {random.choice(['Blue Cross Blue Shield', 'Aetna', 'UnitedHealthcare', 'Self Pay'])}

SERVICE DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Date of Service:  {(bill_date - timedelta(days=random.randint(7, 30))).strftime('%m/%d/%Y')}
Provider:         Dr. {random.choice(LAST_NAMES)}, {random.choice(['MD', 'DO', 'NP', 'PA'])}

PROCEDURES AND CHARGES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Code    Description                                    Charge      Insurance    You Owe
────────────────────────────────────────────────────────────────────────────────────────
"""
            total_charge = 0
            total_insurance = 0
            total_patient = 0
            
            for i in range(random.randint(1, 5)):
                proc_name, charge, patient_owes = random.choice(self.PROCEDURES)
                insurance_pays = charge - patient_owes
                code = f"{random.randint(10000, 99999)}"
                content += f"{code}  {proc_name:<45} ${charge:>8,.2f}   ${insurance_pays:>8,.2f}   ${patient_owes:>7,.2f}\n"
                total_charge += charge
                total_insurance += insurance_pays
                total_patient += patient_owes
            
            content += f"""
────────────────────────────────────────────────────────────────────────────────────────
TOTALS:                                              ${total_charge:>8,.2f}   ${total_insurance:>8,.2f}   ${total_patient:>7,.2f}

PAYMENT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Charges:                                      ${total_charge:>10,.2f}
Insurance Payments/Adjustments:                     -${total_insurance:>10,.2f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AMOUNT DUE:                                         ${total_patient:>10,.2f}

PAYMENT DUE BY: {(bill_date + timedelta(days=30)).strftime('%B %d, %Y')}
"""
            
            filename = f"medical_bill_{provider.replace(' ', '_').lower()}_{bill_date.strftime('%Y_%m_%d')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append(filepath)
        return files


class UtilityBillGenerator(DocumentGenerator):
    """Generate dummy utility bills."""
    
    UTILITIES = [
        ("Arizona Public Service", "Electric", "Phoenix, AZ 85001"),
        ("Salt River Project", "Electric", "Tempe, AZ 85284"),
        ("Southwest Gas", "Gas", "Phoenix, AZ 85072"),
        ("City of Phoenix Water", "Water", "Phoenix, AZ 85003"),
        ("Cox Communications", "Internet/Cable", "Phoenix, AZ 85034"),
    ]
    
    def generate(self, count: int = 1) -> List[Path]:
        files = []
        for _ in range(count):
            utility, service_type, location = random.choice(self.UTILITIES)
            doc_id = self.generate_doc_id()
            bill_date = datetime.now() - timedelta(days=random.randint(1, 90))
            
            content = f"""
{'='*80}
                          {utility.upper()}
                        {service_type.upper()} SERVICE BILL
{'='*80}

{utility}
Billing Department
{location}
Customer Service: 1-800-{random.randint(100, 999)}-{random.randint(1000, 9999)}

BILLING INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Account Number:   {random.randint(100000000, 999999999)}
Bill Date:        {bill_date.strftime('%B %d, %Y')}
Service Period:   {(bill_date - timedelta(days=30)).strftime('%m/%d/%Y')} - {bill_date.strftime('%m/%d/%Y')}
Due Date:         {(bill_date + timedelta(days=15)).strftime('%B %d, %Y')}

SERVICE ADDRESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{fake_address()}

ACCOUNT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Previous Balance:                                   ${random.uniform(80, 300):>10,.2f}
Payments Received:                                  -${random.uniform(80, 300):>10,.2f}
Current Charges:                                    ${random.uniform(50, 400):>10,.2f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Amount Due:                                   ${random.uniform(50, 400):>10,.2f}

This utility bill is generated for testing purposes only.
"""
            
            filename = f"utility_bill_{utility.replace(' ', '_').lower()}_{bill_date.strftime('%Y_%m')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append(filepath)
        return files


class TaxDocumentGenerator(DocumentGenerator):
    """Generate dummy tax documents."""
    
    def generate_w2(self, count: int = 1) -> List[Path]:
        files = []
        tax_year = datetime.now().year - 1
        
        for _ in range(count):
            doc_id = self.generate_doc_id()
            employer = fake_company()
            employee = fake_name()
            wages = random.uniform(35000, 150000)
            
            content = f"""
{'='*80}
                    W-2 WAGE AND TAX STATEMENT {tax_year}
{'='*80}

                           ▓▓▓▓  ⚠️  DUMMY TAX DOCUMENT - NOT REAL  ⚠️  ▓▓▓▓

Employer: {employer}
Employee: {employee}
SSN: {fake_ssn()}

WAGE AND TAX INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Box 1 - Wages, tips, other compensation:              ${wages:>12,.2f}
Box 2 - Federal income tax withheld:                  ${wages * 0.12:>12,.2f}
Box 3 - Social Security wages:                        ${min(wages, 168600):>12,.2f}
Box 4 - Social Security tax withheld:                 ${min(wages, 168600) * 0.062:>12,.2f}
Box 5 - Medicare wages and tips:                      ${wages:>12,.2f}
Box 6 - Medicare tax withheld:                        ${wages * 0.0145:>12,.2f}

This is a test document. Do not use for actual tax filing.
"""
            
            filename = f"tax_w2_{employer.replace(' ', '_').lower()}_{tax_year}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append(filepath)
        return files


class CreditCardStatementGenerator(DocumentGenerator):
    """Generate dummy credit card statements."""
    
    ISSUERS = [
        ("Chase Freedom", "Chase Bank USA, N.A."),
        ("Citi Double Cash", "Citibank, N.A."),
        ("Amex Blue Cash", "American Express"),
        ("Discover It", "Discover Bank"),
    ]
    
    def generate(self, count: int = 1) -> List[Path]:
        files = []
        for _ in range(count):
            card_name, issuer = random.choice(self.ISSUERS)
            doc_id = self.generate_doc_id()
            stmt_date = datetime.now() - timedelta(days=random.randint(1, 730))
            
            content = f"""
{'='*80}
                         {card_name.upper()}
                        CREDIT CARD STATEMENT
{'='*80}

{issuer}
Customer Service: 1-800-{random.randint(100, 999)}-{random.randint(1000, 9999)}

STATEMENT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Statement Date:   {stmt_date.strftime('%B %d, %Y')}
Card Number:      ****-****-****-{random.randint(1000, 9999)}
Cardholder:       {fake_name()}

Account Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Previous Balance:                                   ${random.uniform(500, 3000):>10,.2f}
Payments/Credits:                                   -${random.uniform(400, 3000):>10,.2f}
Purchases/Charges:                                  ${random.uniform(200, 2500):>10,.2f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NEW BALANCE:                                        ${random.uniform(100, 4000):>10,.2f}

Minimum Payment Due:                                ${random.uniform(25, 150):>10,.2f}
Payment Due Date:                                   {(stmt_date + timedelta(days=25)).strftime('%B %d, %Y')}

This credit card statement is generated for testing purposes only.
"""
            
            filename = f"credit_card_{card_name.replace(' ', '_').lower()}_{stmt_date.strftime('%Y_%m')}_{doc_id}.txt"
            filepath = self.save(filename, content, doc_id)
            files.append(filepath)
        return files


def generate_all_test_data(output_dir: Path, count_per_type: int = 5) -> dict:
    """Generate comprehensive test data set."""
    results = {}
    
    print("Generating bank statements...")
    bank_gen = BankStatementGenerator(output_dir / "bank_statements")
    results['bank_statements'] = bank_gen.generate(count_per_type)
    
    print("Generating medical bills...")
    medical_gen = MedicalBillGenerator(output_dir / "medical_bills")
    results['medical_bills'] = medical_gen.generate(count_per_type)
    
    print("Generating utility bills...")
    utility_gen = UtilityBillGenerator(output_dir / "utility_bills")
    results['utility_bills'] = utility_gen.generate(count_per_type)
    
    print("Generating tax documents...")
    tax_gen = TaxDocumentGenerator(output_dir / "tax_documents")
    results['tax_w2'] = tax_gen.generate_w2(count_per_type)
    
    print("Generating credit card statements...")
    cc_gen = CreditCardStatementGenerator(output_dir / "credit_card_statements")
    results['credit_card_statements'] = cc_gen.generate(count_per_type)
    
    return results


def main():
    parser = argparse.ArgumentParser(description="Generate test data for File Organizer")
    parser.add_argument('--output', '-o', type=Path, default=Path(__file__).parent,
                        help='Output directory for test files')
    parser.add_argument('--count', '-c', type=int, default=5,
                        help='Number of files per document type')
    
    args = parser.parse_args()
    
    print(f"Generating test data in: {args.output.absolute()}")
    print(f"Files per type: {args.count}")
    print()
    
    results = generate_all_test_data(args.output, args.count)
    
    print()
    print("="*60)
    print("TEST DATA GENERATION COMPLETE")
    print("="*60)
    
    total_files = sum(len(files) for files in results.values())
    for doc_type, files in results.items():
        print(f"{doc_type.replace('_', ' ').title()}: {len(files)} files")
    
    print(f"\nTotal files generated: {total_files}")
    print("\n⚠️  IMPORTANT: All files are marked as NOT REAL / TEST DATA")


if __name__ == "__main__":
    main()
